[project]
name = "cadmium"
version = "0.1.0"
description = "Add a short description here"
authors = ["Aleks Rūtiņš <aleks@rutins.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = { cmd = [
    "meson",
    "setup",
    ".build"
] }

build = { cmd = ["meson", "compile", "-C", ".build"], depends_on = ["configure"] }

test = { cmd = [".build/test/cadmium_test"], depends_on = ["build"] }

[dependencies]
cxx-compiler = "1.6.0.*"
meson = "1.3.0.*"
ninja = "1.11.1.*"
gtest = "1.14.0.*"
sdl2 = "2.28.4.*"
